CREATE TABLE tblType (
  idType CHAR(4) PRIMARY KEY,
  dtCreateDate  DATETIME     DEFAULT CURRENT_TIMESTAMP,
  dtUpdateDate  DATETIME ON UPDATE CURRENT_TIMESTAMP
)
  ENGINE = InnoDB;

CREATE TABLE tblMessage (
  idMessage     INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  dtDescription VARCHAR(200) NOT NULL,
  dtCreateDate  DATETIME     DEFAULT CURRENT_TIMESTAMP,
  dtUpdateDate  DATETIME ON UPDATE CURRENT_TIMESTAMP,
  fiType        CHAR(4)      NOT NULL,

  CONSTRAINT fk_Type_tblMessage
  FOREIGN KEY (fiType)
  REFERENCES tblType (idType)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)
  ENGINE = InnoDB;

CREATE TABLE tblLanguage (
  idLanguage   CHAR(2)     NOT NULL PRIMARY KEY,
  dtName       VARCHAR(50) NOT NULL,
  dtCreateDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  dtUpdateDate DATETIME ON UPDATE CURRENT_TIMESTAMP
)
  ENGINE = InnoDB;


CREATE TABLE tblMessageLanguage (
  fiMessage    INT UNSIGNED        NOT NULL,
  fiLanguage   CHAR(2)             NOT NULL,
  dtText       VARCHAR(255) UNIQUE NOT NULL,
  dtCreateDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  dtUpdateDate DATETIME ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (fiMessage, fiLanguage),

  CONSTRAINT fk_Message_tblMessageLanguage
  FOREIGN KEY (fiMessage)
  REFERENCES tblMessage (idMessage)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT fk_Language_tblMessageLanguage
  FOREIGN KEY (fiLanguage)
  REFERENCES tblLanguage (idLanguage)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)
  ENGINE = InnoDB;


CREATE TABLE tblTypeLanguage (
  fiType       CHAR(4)      NOT NULL,
  fiLanguage   CHAR(2)      NOT NULL,
  dtText       VARCHAR(255) NOT NULL,
  dtCreateDate DATETIME DEFAULT CURRENT_TIMESTAMP,
  dtUpdateDate DATETIME ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (fiType, fiLanguage),

  CONSTRAINT fk_Type_tblTypeLanguage
  FOREIGN KEY (fiType)
  REFERENCES tblType (idType)
    ON UPDATE CASCADE
    ON DELETE NO ACTION,

  CONSTRAINT fk_Language_blTypeLanguage
  FOREIGN KEY (fiLanguage)
  REFERENCES tblLanguage (idLanguage)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS tblChanges (
  idChanges INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  dtUser    VARCHAR(255) NOT NULL,
  dtTable   VARCHAR(255) NOT NULL,
  dtColumn  VARCHAR(255) NOT NULL,
  dtOld     VARCHAR(255) NOT NULL,
  dtNew     VARCHAR(255) NOT NULL,
  dtDate    DATETIME                 DEFAULT CURRENT_TIMESTAMP
)
  ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS tblRemovals (
  idChanges INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  dtUser    VARCHAR(255) NOT NULL,
  dtTable   VARCHAR(255) NOT NULL,
  dtRow     VARCHAR(255) NOT NULL,
  dtDate    DATETIME                 DEFAULT CURRENT_TIMESTAMP
)
  ENGINE = InnoDB;
